app:
  name: "zim.conn"
logger:
  level: "debug"
  filename: "logs/app.log"
  maxSize: 100
  maxBackups: 10
  maxAge: 7
  compress: true
server:
  tcpAddr: ":2001"
  wsAddr: ":2002"
registry:
  basePath: "/zoo"
  etcdAddr:
    - "127.0.0.1:2379"
nats:
  addr: "nats://127.0.0.1:4222"
